### ISSUE TITLE
Blog Header needs design. 

### ISSUE THREAD

**Issue by benarent** [gravitational/blog#40]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/559288/155390199-2c034f6d-5e4f-4b05-86f7-62a5d0ae414f.png">

We've a lot of extra whitespace in the header, and the background 'page' doesn't fade nicely 

Preview: https://blog-git-benarent-seosaml-gravitational.vercel.app/blog/how-saml-authentication-works/

**Comment by C-STYR** [comment]
Moved to Asana
